name: Docker Image CI

on:
  push:
    branches:
      - deploy

jobs:

  build:

    runs-on: ubuntu-latest

    # Set the working directory for all steps in this job
    defaults:
      run:
        working-directory: RefferalLink

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: list files
      run: pwd
      
    - name: list files
      run: ls

    - name: Build the Docker image
      run: docker build . --file Dockerfile -t maynghien/referallink

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push maynghien/referallink
